import { NgModule }      		from '@angular/core';
import { BrowserModule } 		from '@angular/platform-browser';
import { FormsModule }   		from '@angular/forms';
import { ReactiveFormsModule } from '@angular/forms';
import { HttpModule }    		from '@angular/http';

import {BrowserAnimationsModule} from '@angular/platform-browser/animations'
import { MaterialModule } 		from '@angular/material';

import { CalendarModule }            from 'primeng/components/calendar/calendar';
import { NgUploaderModule }        from 'ngx-uploader';

import  'hammerjs';




import {LoginComponent} from './login/rt-login.component';
//import {RtRegisterCompletion} from './register/rt-register-completion.component';

import {getKeyValuePair}        from './_pipes/key-value.pipe';
import {objValuesPipe}          from '../app/_pipes/key-value.pipe';
import {rtFileUploaderComponent} from './rtForm/rt-file-uploader.component';

import {rtInputComponent}       from './rtForm/rt-input.component';
import {rtGridBoxAddComponent}     from './rtForm/rt-grid-box-add.component';


import { LmuUserApdComponent } 	from './lmu_uaForm/ua-apd.component';
import { LmuUserPeComponent } 	from './lmu_uaForm/ua-pe.component';
import { LmuUserOpeComponent } 	from './lmu_uaForm/ua-ope.component';
import { LmuUserOiComponent } 	from './lmu_uaForm/ua-oi.component';


import { RestService } from './_services/rt-rest.service';
import {AuthenticationService} from './_services/rt-authentication.service';
import {RtFormService} from './_services/rt-forms.service'
import {ServerConfigs} from './_models/configFile';

import {DialogsService} from './_services/dialogs.services'
import { uaFormDialog} from './modal/uaFormModal.component';

import {lmu_ua_formList} from './_models/lmu_ua_formList'; //TODO

import { UserApplicationComponent }   from './lmu_uaForm/user-application.component';

//import { AppComponent} 			from './app.component';
import {StartPageComponent} from './home/start-page.component';
import { AppLoginComponent} 			from './appLogin.component';
import { AppRoutingModule }             from './app-routing';



    var importsList = [
        BrowserModule,
        FormsModule,
        ReactiveFormsModule,
        MaterialModule,
        HttpModule,
        CalendarModule,

        NgUploaderModule,

        AppRoutingModule,

        BrowserAnimationsModule
        //MaterialModule.forRoot(),
        //ModalModule.forRoot(),
        ];

    var declarationList = [
        //AppComponent,

        AppLoginComponent,
        StartPageComponent,
        LoginComponent,

        //RtRegisterCompletion,

        uaFormDialog,
        UserApplicationComponent,
        LmuUserApdComponent,
        LmuUserPeComponent,
        LmuUserOpeComponent,
        LmuUserOiComponent,
        rtFileUploaderComponent,
        rtInputComponent,
        rtGridBoxAddComponent,
        objValuesPipe,
        getKeyValuePair];

    var providersList = [//UserDataService,
        RestService,
        AuthenticationService,
        ServerConfigs,
        lmu_ua_formList,
        RtFormService,
        DialogsService

        // providers used to create fake backend
        //fakeBackendProviderArray,

        //fakeBackendProvider,
        //MockBackend,
        //BaseRequestOptions
        //Window
        //{provide: Window, useValue: window}
        //WindowRef
        ];

        /********* Note that uaFormDialog has been added to the entryComponents array. ********************************
        *** You need to add any component that is dynamically generated by the component factory resolver to this array.
        ******/
    var entryComponentsList=[
        uaFormDialog
        ];

    var bootstrapList = [AppLoginComponent];
    //var bootstrapList = [AppComponent];



@NgModule({
    imports: [ ...importsList ],
    declarations: [ ...declarationList ],
    providers: [ ...providersList],
    entryComponents : [...entryComponentsList],
    bootstrap: [...bootstrapList]
})




    export class AppModule {
    }
